# Generated by Django 5.2.5 on 2025-08-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_payment_method_alter_order_courier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('completed', 'Bajardi'), ('cancelled', 'Bekor qilingan'), ('perechesleniya', 'Perechesleniya')], default='pending', max_length=20),
        ),
    ]
