# Generated by Django 5.2.6 on 2025-10-22 07:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Buyurtma', 'verbose_name_plural': 'Buyurtmalar'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.AddField(
            model_name='order',
            name='inquantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='outquantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='OrderPhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text="Qo'shimcha telefon raqam", max_length=20, validators=[django.core.validators.RegexValidator(message="Telefon raqam noto'g'ri formatda. Masalan: +998901234567", regex='^\\+?[0-9\\s\\-\\(\\)]{7,20}$')])),
                ('description', models.CharField(blank=True, help_text="Kimning raqami (masalan: ota, ona, qo'shni)", max_length=100, null=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Asosiy telefon raqammi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='orders.order')),
            ],
            options={
                'verbose_name': 'Buyurtma telefon raqami',
                'verbose_name_plural': 'Buyurtma telefon raqamlari',
                'ordering': ['-is_primary', 'created_at'],
            },
        ),
    ]
