# Generated by Django 5.2.6 on 2025-11-05 16:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_options_remove_order_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='effective_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, default=17000.0, help_text='Bir dona uchun narx', max_digits=10),
        ),
        migrations.DeleteModel(
            name='OrderPhoneNumber',
        ),
    ]
