# Generated by Django 5.2.6 on 2025-09-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
    ]
