# Generated by Django 5.2.6 on 2025-10-22 08:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_caption'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientPhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Mijoz telefon raqami', max_length=20, validators=[django.core.validators.RegexValidator(message="Telefon raqam noto'g'ri formatda. Masalan: +998901234567", regex='^\\+?[0-9\\s\\-\\(\\)]{7,20}$')])),
                ('description', models.CharField(blank=True, help_text="Kimning raqami (masalan: ota, ona, qo'shni)", max_length=100, null=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Asosiy telefon raqammi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='clients.client')),
            ],
            options={
                'verbose_name': 'Mijoz telefon raqami',
                'verbose_name_plural': 'Mijoz telefon raqamlari',
                'ordering': ['-is_primary', 'created_at'],
            },
        ),
    ]
