# Generated by Django 5.2.6 on 2025-10-22 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_clientphonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='phone_number',
        ),
    ]
