# Generated by Django 5.2.6 on 2025-12-17 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Sana')),
                ('route_data', models.JSONField(default=list, help_text='Marshrut koordinatalari va tartib', verbose_name="Marshrut ma'lumotlari")),
                ('color', models.CharField(default='#2563eb', help_text='Hex format: #RRGGBB', max_length=7, verbose_name='Marshrut rangi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to=settings.AUTH_USER_MODEL, verbose_name='Kuryer')),
            ],
            options={
                'verbose_name': 'Kuryer marshruty',
                'verbose_name_plural': 'Kuryer marshrutlari',
                'ordering': ['-date', 'courier__username'],
                'unique_together': {('courier', 'date')},
            },
        ),
    ]
