# Generated by Django 5.2.5 on 2025-08-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Karta'), ('cash', 'Naqd'), ('perechesleniya', 'Perechesleniya')], default='cash', help_text="To'lov usuli: Karta yoki Naqd", max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('completed', 'Bajardi'), ('cancelled', 'Bekor qilingan')], default='pending', max_length=20),
        ),
    ]
