# Generated by Django 5.2.6 on 2025-12-22 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_effective_date_alter_order_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Karta'), ('cash', 'Naqd'), ('perechesleniya', 'Perechesleniya'), ('debt', 'Qarz')], default='cash', help_text="To'lov usuli: Karta yoki Naqd", max_length=20),
        ),
    ]
