# Generated by Django 5.2.8 on 2026-01-03 05:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_alter_client_name_client_unique_client_name'),
        ('orders', '0009_alter_order_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['effective_date', 'status'], name='order_date_status_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['client', 'effective_date'], name='order_client_date_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['courier', 'effective_date'], name='order_courier_date_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'payment_method'], name='order_status_payment_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-created_at'], name='order_created_idx'),
        ),
    ]
